// Generated by gencpp from file dummy_grid/DrawGrid.msg
// DO NOT EDIT!


#ifndef DUMMY_GRID_MESSAGE_DRAWGRID_H
#define DUMMY_GRID_MESSAGE_DRAWGRID_H

#include <ros/service_traits.h>


#include <dummy_grid/DrawGridRequest.h>
#include <dummy_grid/DrawGridResponse.h>


namespace dummy_grid
{

struct DrawGrid
{

typedef DrawGridRequest Request;
typedef DrawGridResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DrawGrid
} // namespace dummy_grid


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dummy_grid::DrawGrid > {
  static const char* value()
  {
    return "58bbaa800dd9242d5466364decd790f6";
  }

  static const char* value(const ::dummy_grid::DrawGrid&) { return value(); }
};

template<>
struct DataType< ::dummy_grid::DrawGrid > {
  static const char* value()
  {
    return "dummy_grid/DrawGrid";
  }

  static const char* value(const ::dummy_grid::DrawGrid&) { return value(); }
};


// service_traits::MD5Sum< ::dummy_grid::DrawGridRequest> should match 
// service_traits::MD5Sum< ::dummy_grid::DrawGrid > 
template<>
struct MD5Sum< ::dummy_grid::DrawGridRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dummy_grid::DrawGrid >::value();
  }
  static const char* value(const ::dummy_grid::DrawGridRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dummy_grid::DrawGridRequest> should match 
// service_traits::DataType< ::dummy_grid::DrawGrid > 
template<>
struct DataType< ::dummy_grid::DrawGridRequest>
{
  static const char* value()
  {
    return DataType< ::dummy_grid::DrawGrid >::value();
  }
  static const char* value(const ::dummy_grid::DrawGridRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dummy_grid::DrawGridResponse> should match 
// service_traits::MD5Sum< ::dummy_grid::DrawGrid > 
template<>
struct MD5Sum< ::dummy_grid::DrawGridResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dummy_grid::DrawGrid >::value();
  }
  static const char* value(const ::dummy_grid::DrawGridResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dummy_grid::DrawGridResponse> should match 
// service_traits::DataType< ::dummy_grid::DrawGrid > 
template<>
struct DataType< ::dummy_grid::DrawGridResponse>
{
  static const char* value()
  {
    return DataType< ::dummy_grid::DrawGrid >::value();
  }
  static const char* value(const ::dummy_grid::DrawGridResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUMMY_GRID_MESSAGE_DRAWGRID_H
