// Generated by gencpp from file dummy_grid/DrawGridResponse.msg
// DO NOT EDIT!


#ifndef DUMMY_GRID_MESSAGE_DRAWGRIDRESPONSE_H
#define DUMMY_GRID_MESSAGE_DRAWGRIDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dummy_grid
{
template <class ContainerAllocator>
struct DrawGridResponse_
{
  typedef DrawGridResponse_<ContainerAllocator> Type;

  DrawGridResponse_()
    {
    }
  DrawGridResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::dummy_grid::DrawGridResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dummy_grid::DrawGridResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DrawGridResponse_

typedef ::dummy_grid::DrawGridResponse_<std::allocator<void> > DrawGridResponse;

typedef boost::shared_ptr< ::dummy_grid::DrawGridResponse > DrawGridResponsePtr;
typedef boost::shared_ptr< ::dummy_grid::DrawGridResponse const> DrawGridResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dummy_grid::DrawGridResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dummy_grid::DrawGridResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dummy_grid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'dummy_grid': ['/home/cras/python/aro/hw3/src/dummy_grid/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dummy_grid::DrawGridResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dummy_grid::DrawGridResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dummy_grid::DrawGridResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dummy_grid::DrawGridResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dummy_grid::DrawGridResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dummy_grid::DrawGridResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dummy_grid::DrawGridResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::dummy_grid::DrawGridResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::dummy_grid::DrawGridResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dummy_grid/DrawGridResponse";
  }

  static const char* value(const ::dummy_grid::DrawGridResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dummy_grid::DrawGridResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::dummy_grid::DrawGridResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dummy_grid::DrawGridResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrawGridResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dummy_grid::DrawGridResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::dummy_grid::DrawGridResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DUMMY_GRID_MESSAGE_DRAWGRIDRESPONSE_H
