// Generated by gencpp from file dummy_grid/DrawGridRequest.msg
// DO NOT EDIT!


#ifndef DUMMY_GRID_MESSAGE_DRAWGRIDREQUEST_H
#define DUMMY_GRID_MESSAGE_DRAWGRIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dummy_grid/ValuePoint.h>

namespace dummy_grid
{
template <class ContainerAllocator>
struct DrawGridRequest_
{
  typedef DrawGridRequest_<ContainerAllocator> Type;

  DrawGridRequest_()
    : points()  {
    }
  DrawGridRequest_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::dummy_grid::ValuePoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dummy_grid::ValuePoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::dummy_grid::DrawGridRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dummy_grid::DrawGridRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DrawGridRequest_

typedef ::dummy_grid::DrawGridRequest_<std::allocator<void> > DrawGridRequest;

typedef boost::shared_ptr< ::dummy_grid::DrawGridRequest > DrawGridRequestPtr;
typedef boost::shared_ptr< ::dummy_grid::DrawGridRequest const> DrawGridRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dummy_grid::DrawGridRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dummy_grid::DrawGridRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dummy_grid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'dummy_grid': ['/home/cras/python/aro/hw3/src/dummy_grid/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dummy_grid::DrawGridRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dummy_grid::DrawGridRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dummy_grid::DrawGridRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dummy_grid::DrawGridRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dummy_grid::DrawGridRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dummy_grid::DrawGridRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dummy_grid::DrawGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58bbaa800dd9242d5466364decd790f6";
  }

  static const char* value(const ::dummy_grid::DrawGridRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58bbaa800dd9242dULL;
  static const uint64_t static_value2 = 0x5466364decd790f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dummy_grid::DrawGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dummy_grid/DrawGridRequest";
  }

  static const char* value(const ::dummy_grid::DrawGridRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dummy_grid::DrawGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dummy_grid/ValuePoint[] points\n\
\n\
================================================================================\n\
MSG: dummy_grid/ValuePoint\n\
int16 x\n\
int16 y\n\
int8 value\n\
";
  }

  static const char* value(const ::dummy_grid::DrawGridRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dummy_grid::DrawGridRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrawGridRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dummy_grid::DrawGridRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dummy_grid::DrawGridRequest_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dummy_grid::ValuePoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUMMY_GRID_MESSAGE_DRAWGRIDREQUEST_H
