// Generated by gencpp from file dummy_grid/ValuePoint.msg
// DO NOT EDIT!


#ifndef DUMMY_GRID_MESSAGE_VALUEPOINT_H
#define DUMMY_GRID_MESSAGE_VALUEPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dummy_grid
{
template <class ContainerAllocator>
struct ValuePoint_
{
  typedef ValuePoint_<ContainerAllocator> Type;

  ValuePoint_()
    : x(0)
    , y(0)
    , value(0)  {
    }
  ValuePoint_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef int8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::dummy_grid::ValuePoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dummy_grid::ValuePoint_<ContainerAllocator> const> ConstPtr;

}; // struct ValuePoint_

typedef ::dummy_grid::ValuePoint_<std::allocator<void> > ValuePoint;

typedef boost::shared_ptr< ::dummy_grid::ValuePoint > ValuePointPtr;
typedef boost::shared_ptr< ::dummy_grid::ValuePoint const> ValuePointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dummy_grid::ValuePoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dummy_grid::ValuePoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dummy_grid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'dummy_grid': ['/home/cras/python/aro/hw3/src/dummy_grid/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dummy_grid::ValuePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dummy_grid::ValuePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dummy_grid::ValuePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dummy_grid::ValuePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dummy_grid::ValuePoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dummy_grid::ValuePoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dummy_grid::ValuePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f251dc5cdacac9c0ea3ef6f992e4d62a";
  }

  static const char* value(const ::dummy_grid::ValuePoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf251dc5cdacac9c0ULL;
  static const uint64_t static_value2 = 0xea3ef6f992e4d62aULL;
};

template<class ContainerAllocator>
struct DataType< ::dummy_grid::ValuePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dummy_grid/ValuePoint";
  }

  static const char* value(const ::dummy_grid::ValuePoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dummy_grid::ValuePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n\
int16 y\n\
int8 value\n\
";
  }

  static const char* value(const ::dummy_grid::ValuePoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dummy_grid::ValuePoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ValuePoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dummy_grid::ValuePoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dummy_grid::ValuePoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUMMY_GRID_MESSAGE_VALUEPOINT_H
