// Generated by gencpp from file exploration/AnyFrontiersLeft.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MESSAGE_ANYFRONTIERSLEFT_H
#define EXPLORATION_MESSAGE_ANYFRONTIERSLEFT_H

#include <ros/service_traits.h>


#include <exploration/AnyFrontiersLeftRequest.h>
#include <exploration/AnyFrontiersLeftResponse.h>


namespace exploration
{

struct AnyFrontiersLeft
{

typedef AnyFrontiersLeftRequest Request;
typedef AnyFrontiersLeftResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnyFrontiersLeft
} // namespace exploration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exploration::AnyFrontiersLeft > {
  static const char* value()
  {
    return "9c55a8e73f02e61ed1fd7718907efa64";
  }

  static const char* value(const ::exploration::AnyFrontiersLeft&) { return value(); }
};

template<>
struct DataType< ::exploration::AnyFrontiersLeft > {
  static const char* value()
  {
    return "exploration/AnyFrontiersLeft";
  }

  static const char* value(const ::exploration::AnyFrontiersLeft&) { return value(); }
};


// service_traits::MD5Sum< ::exploration::AnyFrontiersLeftRequest> should match 
// service_traits::MD5Sum< ::exploration::AnyFrontiersLeft > 
template<>
struct MD5Sum< ::exploration::AnyFrontiersLeftRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exploration::AnyFrontiersLeft >::value();
  }
  static const char* value(const ::exploration::AnyFrontiersLeftRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration::AnyFrontiersLeftRequest> should match 
// service_traits::DataType< ::exploration::AnyFrontiersLeft > 
template<>
struct DataType< ::exploration::AnyFrontiersLeftRequest>
{
  static const char* value()
  {
    return DataType< ::exploration::AnyFrontiersLeft >::value();
  }
  static const char* value(const ::exploration::AnyFrontiersLeftRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exploration::AnyFrontiersLeftResponse> should match 
// service_traits::MD5Sum< ::exploration::AnyFrontiersLeft > 
template<>
struct MD5Sum< ::exploration::AnyFrontiersLeftResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exploration::AnyFrontiersLeft >::value();
  }
  static const char* value(const ::exploration::AnyFrontiersLeftResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration::AnyFrontiersLeftResponse> should match 
// service_traits::DataType< ::exploration::AnyFrontiersLeft > 
template<>
struct DataType< ::exploration::AnyFrontiersLeftResponse>
{
  static const char* value()
  {
    return DataType< ::exploration::AnyFrontiersLeft >::value();
  }
  static const char* value(const ::exploration::AnyFrontiersLeftResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXPLORATION_MESSAGE_ANYFRONTIERSLEFT_H
