// Generated by gencpp from file exploration/AnyFrontiersLeftRequest.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MESSAGE_ANYFRONTIERSLEFTREQUEST_H
#define EXPLORATION_MESSAGE_ANYFRONTIERSLEFTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exploration
{
template <class ContainerAllocator>
struct AnyFrontiersLeftRequest_
{
  typedef AnyFrontiersLeftRequest_<ContainerAllocator> Type;

  AnyFrontiersLeftRequest_()
    {
    }
  AnyFrontiersLeftRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AnyFrontiersLeftRequest_

typedef ::exploration::AnyFrontiersLeftRequest_<std::allocator<void> > AnyFrontiersLeftRequest;

typedef boost::shared_ptr< ::exploration::AnyFrontiersLeftRequest > AnyFrontiersLeftRequestPtr;
typedef boost::shared_ptr< ::exploration::AnyFrontiersLeftRequest const> AnyFrontiersLeftRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exploration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration/AnyFrontiersLeftRequest";
  }

  static const char* value(const ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnyFrontiersLeftRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::exploration::AnyFrontiersLeftRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION_MESSAGE_ANYFRONTIERSLEFTREQUEST_H
