// Generated by gencpp from file exploration/AnyFrontiersLeftResponse.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MESSAGE_ANYFRONTIERSLEFTRESPONSE_H
#define EXPLORATION_MESSAGE_ANYFRONTIERSLEFTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exploration
{
template <class ContainerAllocator>
struct AnyFrontiersLeftResponse_
{
  typedef AnyFrontiersLeftResponse_<ContainerAllocator> Type;

  AnyFrontiersLeftResponse_()
    : any_frontiers_left(false)  {
    }
  AnyFrontiersLeftResponse_(const ContainerAllocator& _alloc)
    : any_frontiers_left(false)  {
  (void)_alloc;
    }



   typedef uint8_t _any_frontiers_left_type;
  _any_frontiers_left_type any_frontiers_left;





  typedef boost::shared_ptr< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AnyFrontiersLeftResponse_

typedef ::exploration::AnyFrontiersLeftResponse_<std::allocator<void> > AnyFrontiersLeftResponse;

typedef boost::shared_ptr< ::exploration::AnyFrontiersLeftResponse > AnyFrontiersLeftResponsePtr;
typedef boost::shared_ptr< ::exploration::AnyFrontiersLeftResponse const> AnyFrontiersLeftResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exploration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c55a8e73f02e61ed1fd7718907efa64";
  }

  static const char* value(const ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c55a8e73f02e61eULL;
  static const uint64_t static_value2 = 0xd1fd7718907efa64ULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration/AnyFrontiersLeftResponse";
  }

  static const char* value(const ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool any_frontiers_left\n\
";
  }

  static const char* value(const ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.any_frontiers_left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnyFrontiersLeftResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration::AnyFrontiersLeftResponse_<ContainerAllocator>& v)
  {
    s << indent << "any_frontiers_left: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.any_frontiers_left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION_MESSAGE_ANYFRONTIERSLEFTRESPONSE_H
