// Generated by gencpp from file exploration/GenerateFrontier.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MESSAGE_GENERATEFRONTIER_H
#define EXPLORATION_MESSAGE_GENERATEFRONTIER_H

#include <ros/service_traits.h>


#include <exploration/GenerateFrontierRequest.h>
#include <exploration/GenerateFrontierResponse.h>


namespace exploration
{

struct GenerateFrontier
{

typedef GenerateFrontierRequest Request;
typedef GenerateFrontierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateFrontier
} // namespace exploration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exploration::GenerateFrontier > {
  static const char* value()
  {
    return "9c696f8357da6184167237a9d05c73bc";
  }

  static const char* value(const ::exploration::GenerateFrontier&) { return value(); }
};

template<>
struct DataType< ::exploration::GenerateFrontier > {
  static const char* value()
  {
    return "exploration/GenerateFrontier";
  }

  static const char* value(const ::exploration::GenerateFrontier&) { return value(); }
};


// service_traits::MD5Sum< ::exploration::GenerateFrontierRequest> should match 
// service_traits::MD5Sum< ::exploration::GenerateFrontier > 
template<>
struct MD5Sum< ::exploration::GenerateFrontierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exploration::GenerateFrontier >::value();
  }
  static const char* value(const ::exploration::GenerateFrontierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration::GenerateFrontierRequest> should match 
// service_traits::DataType< ::exploration::GenerateFrontier > 
template<>
struct DataType< ::exploration::GenerateFrontierRequest>
{
  static const char* value()
  {
    return DataType< ::exploration::GenerateFrontier >::value();
  }
  static const char* value(const ::exploration::GenerateFrontierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exploration::GenerateFrontierResponse> should match 
// service_traits::MD5Sum< ::exploration::GenerateFrontier > 
template<>
struct MD5Sum< ::exploration::GenerateFrontierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exploration::GenerateFrontier >::value();
  }
  static const char* value(const ::exploration::GenerateFrontierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration::GenerateFrontierResponse> should match 
// service_traits::DataType< ::exploration::GenerateFrontier > 
template<>
struct DataType< ::exploration::GenerateFrontierResponse>
{
  static const char* value()
  {
    return DataType< ::exploration::GenerateFrontier >::value();
  }
  static const char* value(const ::exploration::GenerateFrontierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXPLORATION_MESSAGE_GENERATEFRONTIER_H
