// Generated by gencpp from file exploration/GenerateFrontierResponse.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MESSAGE_GENERATEFRONTIERRESPONSE_H
#define EXPLORATION_MESSAGE_GENERATEFRONTIERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace exploration
{
template <class ContainerAllocator>
struct GenerateFrontierResponse_
{
  typedef GenerateFrontierResponse_<ContainerAllocator> Type;

  GenerateFrontierResponse_()
    : goal_pose()  {
    }
  GenerateFrontierResponse_(const ContainerAllocator& _alloc)
    : goal_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _goal_pose_type;
  _goal_pose_type goal_pose;





  typedef boost::shared_ptr< ::exploration::GenerateFrontierResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration::GenerateFrontierResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateFrontierResponse_

typedef ::exploration::GenerateFrontierResponse_<std::allocator<void> > GenerateFrontierResponse;

typedef boost::shared_ptr< ::exploration::GenerateFrontierResponse > GenerateFrontierResponsePtr;
typedef boost::shared_ptr< ::exploration::GenerateFrontierResponse const> GenerateFrontierResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration::GenerateFrontierResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration::GenerateFrontierResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exploration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exploration::GenerateFrontierResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration::GenerateFrontierResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration::GenerateFrontierResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration::GenerateFrontierResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration::GenerateFrontierResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration::GenerateFrontierResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration::GenerateFrontierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c696f8357da6184167237a9d05c73bc";
  }

  static const char* value(const ::exploration::GenerateFrontierResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c696f8357da6184ULL;
  static const uint64_t static_value2 = 0x167237a9d05c73bcULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration::GenerateFrontierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration/GenerateFrontierResponse";
  }

  static const char* value(const ::exploration::GenerateFrontierResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration::GenerateFrontierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D goal_pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::exploration::GenerateFrontierResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration::GenerateFrontierResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateFrontierResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration::GenerateFrontierResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration::GenerateFrontierResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION_MESSAGE_GENERATEFRONTIERRESPONSE_H
