// Generated by gencpp from file exploration/PlanPath.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MESSAGE_PLANPATH_H
#define EXPLORATION_MESSAGE_PLANPATH_H

#include <ros/service_traits.h>


#include <exploration/PlanPathRequest.h>
#include <exploration/PlanPathResponse.h>


namespace exploration
{

struct PlanPath
{

typedef PlanPathRequest Request;
typedef PlanPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanPath
} // namespace exploration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exploration::PlanPath > {
  static const char* value()
  {
    return "0e854b793b5f5c0be0a44ce6a85613ce";
  }

  static const char* value(const ::exploration::PlanPath&) { return value(); }
};

template<>
struct DataType< ::exploration::PlanPath > {
  static const char* value()
  {
    return "exploration/PlanPath";
  }

  static const char* value(const ::exploration::PlanPath&) { return value(); }
};


// service_traits::MD5Sum< ::exploration::PlanPathRequest> should match 
// service_traits::MD5Sum< ::exploration::PlanPath > 
template<>
struct MD5Sum< ::exploration::PlanPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exploration::PlanPath >::value();
  }
  static const char* value(const ::exploration::PlanPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration::PlanPathRequest> should match 
// service_traits::DataType< ::exploration::PlanPath > 
template<>
struct DataType< ::exploration::PlanPathRequest>
{
  static const char* value()
  {
    return DataType< ::exploration::PlanPath >::value();
  }
  static const char* value(const ::exploration::PlanPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exploration::PlanPathResponse> should match 
// service_traits::MD5Sum< ::exploration::PlanPath > 
template<>
struct MD5Sum< ::exploration::PlanPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exploration::PlanPath >::value();
  }
  static const char* value(const ::exploration::PlanPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration::PlanPathResponse> should match 
// service_traits::DataType< ::exploration::PlanPath > 
template<>
struct DataType< ::exploration::PlanPathResponse>
{
  static const char* value()
  {
    return DataType< ::exploration::PlanPath >::value();
  }
  static const char* value(const ::exploration::PlanPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXPLORATION_MESSAGE_PLANPATH_H
